version: "3.8"
 
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: granja
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
  app:
    build: .
    depends_on:
      - db
    stdin_open: true
    tty: true